### ISSUE TITLE
Empty initial steps

### ISSUE THREAD

**Issue by gilbarbara** [jakemmarsh/react-tour-guide#3]
Hey!

Is there a way to start the mixin with no initial steps and add them with `setTourSteps`  as they are loaded? I've tried that but it immediately called the callback and throwed some violation errors.
My main components load their data from an api so there are no visible elements on `componentDidMount`..

I'll to fork and code these changes but let me know if have any thoughts on this approach.

[s]

**Comment by jakemmarsh** [comment]
Ah good catch, may not have tested that case previously.

At a quick glance this may be fixed by adding an additional check on [line 52 of the mixin](https://github.com/jakemmarsh/react-tour-guide/blob/master/lib/js/Mixin.js#L52), ensuring that `!hasNewStep && this.settings.steps.length > 0`. I'll have to look into it

**Comment by gilbarbara** [comment]
hey,

I had to change a few other things and set the `startIndex` to -1 for empty starting steps array.

https://github.com/jakemmarsh/react-tour-guide/pull/4

**Comment by jakemmarsh** [comment]
fixed in #4
